### ISSUE TITLE
List of Vapor 3 missing/outdated documentation

### ISSUE THREAD

**Issue by Joannis** [vapor/documentation#242]
- [ ] MySQL
  - [ ] Connecting
  - [ ] Querying
  - [ ] Data binding
  - [ ] Auto-increment
- [ ] Validation
- [ ] Leaf
- [ ] Fluent

**Comment by getaaron** [comment]
I'm new to Vapor so not 100% sure, but it appears https://docs.vapor.codes/2.0/validation/overview/ is outdated

**Comment by kdawgwilk** [comment]
Is Relationships between models included in Fluent?  Also creating custom tags in leaf would be nice to have in the docs

**Comment by axello** [comment]
You might want to add a small paragraph about swiftenv, for people that used the older Vapor, where this was recommended actually: https://vapor.readme.io/v0.12/docs/install-swift-3-swiftenv.
The problem I had yesterday (with Joannis) was caused because swiftenv took over the toolchain command and forced swift 3.1 instead of 4.1.
Vapor was installed with '4.1' in the .swiftversion file, but could not find the actual swift environment, as that was called '4.1-dev'.

**Comment by tanner0101** [comment]
@axello swift env won't be required once Vapor 3 is fully released, but I do agree it would be useful for people while we are in RC phase!
