### ISSUE TITLE
why  `vapor clean` and  add`mysql-provider` will display an error

### ISSUE THREAD

**Issue by zhao95** [vapor/documentation#54]
let package = Package(
    name: "MyApp",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 0),
        .Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)
    ]
)
It's important to vapor clean or vapor build --clean after adding new packages.

I found running`vapor clean`, an error will be reported later, missing dependencies, this attempt to use `vapor build`, there is no mistake.

But add this  `.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)`
problems arising from the lack of how to solve other dependencies.?

Of course, I do not understand English... ...

**Comment by LoganWright** [comment]
@zhao95 Sorry this is happening, I didn't see this until now. In future, slack or Vapor repo are great places to get our attention faster.

Are you using Xcode?

If YES then make sure to regenerate with `vapor xcode` so that it can properly link new libraries.

Please let me know if that resolves your issue.
